[package]
name = "amp"
description = "Amphitheatre's official command line tool"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
documentation = "https://docs.amphitheatre.app/cli/"
repository = "https://github.com/amphitheatre-app/cli"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["components/*"]

[dependencies]
client = {path = "components/client"}
errors = {path = "components/errors"}
schema = {path = "components/schema"}

clap = {version = "4.0.26", features = ["derive"]}
clap-verbosity-flag = "2.0.0"
clap_complete = "4.0.5"
ctrlc = "3.2.3"
log = "0.4.17"
once_cell = "1.16.0"
owo-colors = {version = "3.5.0", features = ["supports-colors"]}
toml = "0.5"
serde_json = "1.0.89"
