[package]
name = "amp"
description = "Amphitheatre's official command line tool"
version = "0.6.3"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
documentation = "https://docs.amphitheatre.app/cli/"
repository = "https://github.com/amphitheatre-app/cli"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

amp-client = { git = "https://github.com/amphitheatre-app/amp-client-rust", tag = "v0.7.7" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.7.8" }

anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.0"
clap_complete = "4.5.1"
colored = "2"
confy = "0.6.1"
ctrlc = "3.4.4"
dunce = "1.0.4"
futures = "0.3"
ignore = "0.4.22"
inquire = "0.7.4"
notify = "6.1.1"
once_cell = "1.19.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
reqwest-eventsource = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.114"
tabled = "0.15.0"
tar = "0.4.40"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
toml = "0.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
