[package]
name = "amp"
description = "Amphitheatre's official command line tool"
version = "0.2.21"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
documentation = "https://docs.amphitheatre.app/cli/"
repository = "https://github.com/amphitheatre-app/cli"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amp-client = { git = "https://github.com/amphitheatre-app/amp-client-rust", tag = "v0.3.1" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.5.0" }
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive", "env"] }
clap-verbosity-flag = "2.0.1"
clap_complete = "4.4.1"
confy = "0.5.1"
ctrlc = "3.4.1"
dunce = "1.0.4"
ignore = "0.4.20"
inquire = "0.6.2"
notify = "6.1.1"
once_cell = "1.18.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
tabled = "0.14.0"
tar = "0.4.40"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
toml = "0.8"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
