[package]
name = "amp"
description = "Amphitheatre's official command line tool"
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
documentation = "https://docs.amphitheatre.app/cli/"
repository = "https://github.com/amphitheatre-app/cli"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amp-client = { git = "https://github.com/amphitheatre-app/amp-client-rust", tag = "v0.9.0" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.9.0" }
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.0"
clap_complete = "4.5.8"
colored = "2.1.0"
confy = "0.6.1"
ctrlc = "3.4.4"
dunce = "1.0.4"
futures = "0.3.30"
ignore = "0.4.22"
inquire = "0.7.5"
notify = "6.1.1"
once_cell = "1.19.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
reqwest-eventsource = "0.6.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tabled = "0.15.0"
tar = "0.4.41"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
