[package]
name = "amp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["components/*"]

[dependencies]
clap = "3.2.23"
lazy_static = "1.4.0"
toml = "0.5"

client = { path = "components/client" }
errors = { path = "components/errors" }
schema = { path = "components/schema" }

ctrlc = "3.2.3"