[package]
edition = "2021"
name = "amp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["components/*"]

[dependencies]
clap = {version = "4.0.26", features = ["derive"]}
clap-verbosity-flag = "2.0.0"
clap_complete = "4.0.5"
toml = "0.5"

client = {path = "components/client"}
errors = {path = "components/errors"}
schema = {path = "components/schema"}

ctrlc = "3.2.3"
