[package]
name = "amp"
description = "Amphitheatre's official command line tool"
version = "0.7.2"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
documentation = "https://docs.amphitheatre.app/cli/"
repository = "https://github.com/amphitheatre-app/cli"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

amp-client = { git = "https://github.com/amphitheatre-app/amp-client-rust", tag = "v0.8.1" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.8.3" }

anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.0"
clap_complete = "4.5.2"
colored = "2.1.0"
confy = "0.6.1"
ctrlc = "3.4.4"
dunce = "1.0.4"
futures = "0.3.30"
ignore = "0.4.22"
inquire = "0.7.5"
notify = "6.1.1"
once_cell = "1.19.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
reqwest-eventsource = "0.6.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.116"
tabled = "0.15.0"
tar = "0.4.40"
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
