name: Build Release Binaries

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: Upload Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
#         - os: windows-latest
#           target: aarch64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cross
    - uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: amp
        archive: $bin-$tag-$target
        target: ${{ matrix.target }}
        token: ${{ secrets.GITHUB_TOKEN }}
